export const ADDITEM = "add_item";
export const DECITEM = "remove_one_item";
export const REMITEM = "remove item";
export const INCITEM = "add one item";
export const RESET = "reset the cart item";
export const SET_URL = "SET_URL"
export const UPDATE_QUANTITY = "updateQuantity"
export const FETCH_ALL_BRANCH_REQUEST = "FETCH_ALL_BRANCH_REQUEST";
export const FETCH_ALL_BRANCH_SUCCESS = "FETCH_ALL_BRANCH_SUCCESS";
export const FETCH_ALL_BRANCH_FAILURE = "FETCH_ALL_BRANCH_FAILURE";
export const FETCH_USERS_CART_REQUEST = "FETCH_USERS_CART_REQUEST";
export const FETCH_USERS_CART_SUCCESS = "FETCH_CART_USERS_SUCCESS";
export const FETCH_USERS_CART_FAILURE = "FETCH_CART_USERS_FAILURE";
export const FETCH_USERS_PROFILE_REQUEST = "FETCH_USERS_PROFILE_REQUEST ";
export const FETCH_USERS_PROFILE_SUCCESS = "FETCH_USERS_PROFILE_SUCCESS ";
export const FETCH_USERS_PROFILE_FAILURE = "FETCH_USERS_PROFILE_FAILURE ";
export const FETCH_ALL_COMP_PRODS_REQUEST = "FETCH_ALL_COMP_PRODS_REQUEST";
export const FETCH_ALL_COMP_PRODS_SUCCESS = "FETCH_ALL_COMP_PRODS_SUCCESS";
export const FETCH_ALL_COMP_PRODS_FAILURE = "FETCH_ALL_COMP_PRODS_FAILURE";


